### ISSUE TITLE
Add example about dynamic experiment results retrieval as JSON

### ISSUE THREAD

**Issue by x-ji** [babe-project/MinimalTemplate#6]
See https://github.com/babe-project/ProComPrag/issues/6

**Comment by michael-franke** [comment]
This is not done, but I created a new issue on this. We should link this to the new functionality of uploading and using data from a pre-given CSV/JSON file. (The new issue is filed under babe-site, because it requires a new template and is mainly about showcasing/communicating the existing functionalities).
